### ISSUE TITLE
[Feature]: GDA (Genome Decomposition Analysis)

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/sequencecomposition#7]
### Which pipeline(s) is your feature request for?

- [ ] insdcdownload
- [ ] ensemblrepeatdownload
- [ ] ensemblgenedownload
- [X] sequencecomposition
- [ ] readmapping
- [ ] variantcalling
- [ ] blobtoolkit
- [ ] genomenote

### Describe the solution you'd like.

Import features from [GDA (Genome Decomposition Analysis)](https://github.com/sanger-tol/gda) pipeline

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muffato** [comment]
Closing as I've created many issues to list all the features that were implemented in the GDA pipeline
